### ISSUE TITLE
Solvency increases as more longs are opened

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive#582]
# Background

`test_long_multiblock_round_trip_end_of_checkpoint` failed on the zeta adjustment branch with the following parameters: 

```
        uint256 apr = 115792089237316195423570985008687907853269984665640564039457583990320674062335;
        uint256 timeStretchApr = 886936259672610464646559504023817532562726574141720139630650341263;
        uint256 basePaid = 65723876150308947051900890891865009457038319412461;
```

As a sanity check, I checked to see what the max long $M$ was (I was working on this recently, so it seemed like a likely culprit). It was $M = 4677333288.780808446462618769$ and was quite a bit larger than the actual $basePaid$ amount of $3981586624.064164508947836781$. With this in mind, I assumed that the max long was too large, and we had picked a value that was smaller than the calculated max long but larger than the true max long. 

To test this hypothesis, I tried to open a long with a `basePaid` equal to the calculated max long. To my surprise, the test passed and the long was opened successfully.

We can simplify the failing test into the following example: 

## Example

1. A Hyperdrive pool is deployed with the following configuration:
    - time stretch rate = 0.852697032603548700
    - curve fee = 0.05
    - flat fee = 0.0005
    - governance fee = 0.015
    - all other parameters are the defaults given by `testConfig(..)`
2. Alice initializes the pool with 500,000,000 DAI at a fixed rate of 0.172749478143121504.
3. Bob opens a long with a base amount of $X$.

If we set $X$ equal to the max long of $4677333288.780808446462618769$, Bob's will successfully open the long. If instead we set $X$ equal to 90% of the max long, $0.9 \cdot 4677333288.780808446462618769 = 4209599959.902727601816356892$, Bob's transaction will revert with an error of `BaseBufferExceedsShareReserves`. 

To rule out the possibility that all trades below a certain size fail due to insolvency, I tried setting $X$ to 1% of the max long, $X = 0.01 \cdot 4677333288.780808446462618769 = 46773332.887808084464626187$. This succeeded, which made it clear that there are three regimes to consider:
1. The regime between the minimum trade size and the false max long. The false max long is the smallest value between the minimum trade size and the max long such that the pool's solvency equals 0.
2. The regime between the false max long and the upper bound of the false max longs.
3. The regime between the upper bound of the false max longs and the true max long. 

# Logs

To start the process of investigating the issue, I collected logs from the test with two different $X$ values:

## $X = 0.9 \cdot M$

```
Running 1 test for test/integrations/hyperdrive/RoundTripTest.t.sol:RoundTripTest
[FAIL. Reason: BaseBufferExceedsShareReserves()] test_long_multiblock_round_trip_end_of_checkpoint() (gas: 9414139)
Logs:
  apr = 0.172749478143121504
  timeStretchApr = 0.059533226581802566
  test: 1
  spot price = 0.852697032603548700
  test: 2
  test: 3
  test: 4
  test: 5
  curve fee = 50000000000000000
  governance fee = 15000000000000000
  calculateMaxLong: 1
  basePaid = 3981586624.064164508947836781
  curve fee = 50000000000000000
  governance fee = 15000000000000000
  calculateMaxLong: 1
  curve fee = 50000000000000000
  governance fee = 15000000000000000
  calculateMaxLong: 1
  max long = 4677333288.780808446462618769
  basePaid = 4209599959.902727601816356892
  openLong: initial market state
  - share reserves   = 500000000.000000000000000000
  - bond reserves    = 10143616924.695877349000000000
  - share adjustment = 0.000000000000000000
  - long exposure    = 0.000000000000000000
  - solvency         = 499999999.000000000000000000

  calculateOpenLong: bondProceeds = bondReservesDelta - totalCurveFee
  calculateOpenLong:              = 4496299629.356991275122815356 - 36360309.813225069232559286
  calculateOpenLong:              = 4459939319.543766205890256070

  calculateOpenLong: bondReservesDelta = bondProceeds + governanceCurveFee
  calculateOpenLong:                   = 4459939319.543766205890256070 + 545404.647198376038488389
  calculateOpenLong:                   = 4460484724.190964581928744459

  calculateOpenLong: shareReservesDelta = _shareAmount - totalGovernanceFee
  calculateOpenLong:                    = 4209599959.902727601816356892 - 465064.924234240629029505
  calculateOpenLong:                    = 4209134894.978493361187327387

  _applyOpenLong: checkpoint.longExposure = 0.000000000000000000
  _applyOpenLong: longExposureDelta = 4710743744.109039050593184753
  _applyOpenLong: checkpoint.longExposure = 4710743744.109039050593184753
  _updateLongExposure: before = 0.000000000000000000
  _updateLongExposure: after  = 4710743744.109039050593184753
  _updateLongExposure: 2
  _updateLongExposure: 3
  _applyOpenLong: ending market state
  - share reserves   = 4709134894.978493361187327387
  - bond reserves    = 5683132200.504912767071255541
  - share adjustment = 0.000000000000000000
  - long exposure    = 4710743744.109039050593184753
  - solvency         = -1608850.130545689405857366
  - spot price       = 0.990096609040411252

  _isSolvent: share price = 1.000000000000000000
  _isSolvent: share reserves = 4709134894.978493361187327387
  _isSolvent: long exposure = 4710743744.109039050593184753

Test result: FAILED. 0 passed; 1 failed; finished in 6.43ms

Failing tests:
Encountered 1 failing test in test/integrations/hyperdrive/RoundTripTest.t.sol:RoundTripTest
[FAIL. Reason: BaseBufferExceedsShareReserves()] test_long_multiblock_round_trip_end_of_checkpoint() (gas: 9414139)
```

## $X = M$

```
Running 1 test for test/integrations/hyperdrive/RoundTripTest.t.sol:RoundTripTest
[PASS] test_long_multiblock_round_trip_end_of_checkpoint() (gas: 9426007)
Logs:
  apr = 0.172749478143121504
  timeStretchApr = 0.059533226581802566
  test: 1
  spot price = 0.852697032603548700
  test: 2
  test: 3
  test: 4
  test: 5
  curve fee = 50000000000000000
  governance fee = 15000000000000000
  calculateMaxLong: 1
  basePaid = 3981586624.064164508947836781
  curve fee = 50000000000000000
  governance fee = 15000000000000000
  calculateMaxLong: 1
  curve fee = 50000000000000000
  governance fee = 15000000000000000
  calculateMaxLong: 1
  max long = 4677333288.780808446462618769
  basePaid = 4677333288.780808446462618769
  openLong: initial market state
  - share reserves   = 500000000.000000000000000000
  - bond reserves    = 10143616924.695877349000000000
  - share adjustment = 0.000000000000000000
  - long exposure    = 0.000000000000000000
  - solvency         = 499999999.000000000000000000

  calculateOpenLong: bondProceeds = bondReservesDelta - totalCurveFee
  calculateOpenLong:              = 4966283635.915068685089383102 - 40400344.236916743591732540
  calculateOpenLong:              = 4925883291.678151941497650562

  calculateOpenLong: bondReservesDelta = bondProceeds + governanceCurveFee
  calculateOpenLong:                   = 4925883291.678151941497650562 + 606005.163553751153875988
  calculateOpenLong:                   = 4926489296.841705692651526550

  calculateOpenLong: shareReservesDelta = _shareAmount - totalGovernanceFee
  calculateOpenLong:                    = 4677333288.780808446462618769 - 516738.804704711810032784
  calculateOpenLong:                    = 4676816549.976103734652585985

  _applyOpenLong: checkpoint.longExposure = 0.000000000000000000
  _applyOpenLong: longExposureDelta = 5174950033.380200148342715139
  _applyOpenLong: checkpoint.longExposure = 5174950033.380200148342715139
  _updateLongExposure: before = 0.000000000000000000
  _updateLongExposure: after  = 5174950033.380200148342715139
  _updateLongExposure: 2
  _updateLongExposure: 3
  _applyOpenLong: ending market state
  - share reserves   = 5176816549.976103734652585985
  - bond reserves    = 5217127627.854171656348473450
  - share adjustment = 0.000000000000000000
  - long exposure    = 5174950033.380200148342715139
  - solvency         = 1866515.595903586309870846
  - spot price       = 0.999589440181557450

  _isSolvent: share price = 1.000000000000000000
  _isSolvent: share reserves = 5176816549.976103734652585985
  _isSolvent: long exposure = 5174950033.380200148342715139
  test: 6
  test: 7
  _updateLongExposure: before = 5174950033.380200148342715139
  _updateLongExposure: after  = 0.000000000000000000
  _updateLongExposure: 1
  test: 8
  test: 9
  test: 10

Test result: ok. 1 passed; 0 failed; finished in 6.78ms
```

# Investigation

A few things can be ruled out immediately:
- In both cases, the bond proceeds are greater than the base paid. This means that the trader isn't receiving an average entry price above 1.
- In both cases, the exposure delta is larger than the share reserves delta.

The latter in particular makes the situation seem more confusing. After thinking about the issue for a while, I thought about comparing the difference between the exposure deltas and the share reserves deltas between the two examples. The differences are:

$$
\Delta z_{1} - \Delta z_{0.9} = 4676816549.976103734652585985 - 4209134894.978493361187327387 = 467681654.99761057
$$

$$
\Delta e_{1} - \Delta e_{0.9} = 5174950033.380200148342715139 - 4710743744.109039050593184753 = 464206289.2711611
$$

From these differences, we can see that the share reserves delta resulting from buying the bonds between $0.9 \cdot M$ and $M$ is greater than the long exposure delta over the same interval. This is an immediate red flag because exposure should always increase by more than the share reserves. This property is important for ensuring that solvency decreases monotonically as the long amount increases.

With this piece of evidence, I considered some causes of this phenomenon. The new `calculateMaxLong` isn't the cause of the problem because the long can be opened on `main` (and the long of $0.9 \cdot M$ _can't_ be opened on `main`). Similarly, the logic surrounding the exposure and share reserves updates looked correct. One idea that came to mind was that it's possible that some of the bonds purchased when the max long is opened are purchased at a negative interest rate _if you consider the curve fees_. 

# Deriving the max spot price

One of the basic invariants that Hyperdrive should enforce is that a trader will never receive negative interest bonds. We enforce this invariant with two checks: the check that the spot price is less than or equal to 1 and the check the minimum output is satisfied. It turns out that if the $\phi_{c} > 0$, it's still possible to buy bonds at a negative interest rate after considering the curve fee. Consider the case of opening the max long. If the max long brings the spot price to 1 and $\phi_{c} > 0$, then some of the bonds they buy are purchased at a price above 1 once you apply the curve fee. 

For a base amount of $x$, the bond proceeds of opening a long are given by $y(x) = y_{YS}(x) - c(x)$ where $y_{YS}(x)$ is equal to the bond amount priced by YieldSpace and $c(x)$ is the curve fee given by $c(x) = \phi_{c} \cdot \left( p_0^{-1} - 1 \right) \cdot x$. Let $m$ be the minimum transaction amount and let $M$ be the max amount of base that can be used to open a long. Given these definitions, we can define our negative interest invariant as:

**Negative Interest Invariant**: For all $x_0, x_1 \in [m, M]$ with $x_0 < x_1$ we have that $y(x_1) > y(x_0)$ and that $y(x_1) - y(x_0) \geq x_1 - x_0$.

To be slightly hand-wavy, as $\Delta x = x_1 - x_0$ approaches $0$, $y_{YS}(x_1) - y_{YS}(x_0)$ approaches $p^{-1} \cdot \Delta x$ where $p$ is the spot price after $x_0$ bonds are purchased from the pool. Now we can solve for the condition that our spot price $p$ must satisfy by solving the inequality $y(x_1) - y(x_0) > \Delta x$. We'll start by expanding and simplifying the left hand side of the inequality:

$$
y(x_1) - y(x_0) = (y_{YS}(x_1) - c(x_1)) - (y_{YS}(x_0) - c(x_0)) = (y_{YS}(x_1) - y_{YS}(x_0)) - (c(x_1) - c(x_0))
$$

Substituting our infinitesimal value for $y_{YS}(x_1) - y_{YS}(x_0)$ and expanding $c(x_1) - c(x_0)$ gives us:

$$
y(x_1) - y(x_0) = p^{-1} \cdot \Delta x - \phi_{c} \cdot \left( p_0^{-1} - 1 \right) \cdot \Delta x
$$

Thus our full inequality becomes:

$$
p^{-1} \cdot \Delta x - \phi_{c} \cdot \left( p_0^{-1} - 1 \right) \cdot \Delta x \geq \Delta x
$$

Solving this for $p$ gives us a bound on our spot price of:

$$
p \leq \frac{1}{1 + \phi_{c} \cdot \left( p_0^{-1} - 1 \right)}
$$

# Sanity Checking the constraint

We want to make sure that if we add this constraint, we have ruled out negative interest. Let's say that we open a long position with $x$ base at a spot price $p$ that satisfies the constraint above. The amount of bonds we'll get at this spot price gives us:

$$
y_{YS}(x) = p^{-1} \cdot x \geq (1 + \phi_{c} \cdot \left( p_0^{-1} - 1 \right)) \cdot x
$$

The full amount of bonds the trader will receive is given by $y(x) = y_{YS}(x) - \phi_{c} \cdot \left( p_0^{-1} - 1 \right) \cdot x$. Using our inequality from before, this becomes:

$$
y(x) \geq (1 + \phi_{c} \cdot \left( p_0^{-1} - 1 \right)) \cdot x - \phi_{c} \cdot \left( p_0^{-1} - 1 \right) \cdot x = x
$$

This shows that enforcing this constraint ensures that the trader will not receive negative interest.
